graph TD
start --> |bhl_fetch.php | A(Content from BHL)
A --> |bhl2doc.php| B(convert BHL JSON to doc with tables of contents with text)
B --> |doc2toc.php| C(use ChatGPT to parse table of contents and store results in doc.toc)
C --> |doc2text.php| D(make sure pages in doc.toc have text)
D --> | toc2match.php| E(compare title in doc.toc with text on corresponding page, delete pages that don't match)
E --> | toc2parts.php| F(for each page remaining in toc, send text to ChatGPT to extract article metadata and storew in doc.parts)
F --> | dedup.php| G(filter out obvious duplicates in doc.parts based on title matches)
G --> | parts2ris.php |H(export parts in RIS format)
